import { motion } from "framer-motion";
import {
  Brain, Target, Mic, Briefcase, GraduationCap, Users,
  Shield, Heart, Gamepad2, BarChart3, BookOpen, Map,
} from "lucide-react";

const features = [
  { icon: Brain, title: "Career Score", desc: "Quantify your career readiness with a dynamic 0-100 score", color: "text-primary" },
  { icon: Target, title: "Probability Engine", desc: "AI predicts your success chances for any career goal", color: "text-accent" },
  { icon: Map, title: "AI Roadmaps", desc: "Step-by-step career paths generated by AI", color: "text-vedoryn-orange" },
  { icon: Mic, title: "Mock Interviews", desc: "Practice with AI and get detailed performance analysis", color: "text-vedoryn-pink" },
  { icon: Briefcase, title: "Smart Job Match", desc: "AI matches you with opportunities based on your readiness", color: "text-vedoryn-emerald" },
  { icon: GraduationCap, title: "Scholarship Finder", desc: "Never miss a relevant scholarship opportunity again", color: "text-vedoryn-gold" },
  { icon: Users, title: "Mentor Marketplace", desc: "Connect with domain experts for personalized guidance", color: "text-primary" },
  { icon: Shield, title: "Proof Layer", desc: "Verified skills and achievements recruiters can trust", color: "text-vedoryn-cyan" },
  { icon: Heart, title: "Wellness Monitor", desc: "Track burnout risk and maintain sustainable performance", color: "text-vedoryn-pink" },
  { icon: Gamepad2, title: "Gamification", desc: "XP, levels, achievements, and leaderboards to stay motivated", color: "text-vedoryn-orange" },
  { icon: BarChart3, title: "Recruiter Dashboard", desc: "Data-driven hiring with verified candidate profiles", color: "text-vedoryn-emerald" },
  { icon: BookOpen, title: "Study Planner", desc: "AI-generated study schedules with auto-adjustments", color: "text-vedoryn-gold" },
];

export function FeaturesSection() {
  return (
    <section id="features" className="py-24 relative">
      <div className="container mx-auto px-4">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16">
          <span className="text-sm font-medium text-primary uppercase tracking-widest">Features</span>
          <h2 className="font-display text-4xl md:text-5xl font-bold mt-3 mb-4">
            Everything You Need to{" "}
            <span className="text-gradient-royal">Succeed</span>
          </h2>
          <p className="text-muted-foreground max-w-xl mx-auto">
            A complete career intelligence ecosystem — from measurement to opportunity.
          </p>
        </motion.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
          {features.map((f, i) => (
            <motion.div key={f.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }} transition={{ delay: i * 0.05 }}
              className="group p-6 rounded-xl bg-card border border-border hover:shadow-elevated hover:royal-border transition-all duration-300">
              <f.icon className={`w-8 h-8 ${f.color} mb-4 group-hover:scale-110 transition-transform`} />
              <h3 className="font-display font-semibold text-lg mb-2">{f.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
